#!/usr/bin/env bash
# Fetch reference sources with opensrc and write an index of their cached paths.
set -euo pipefail
command -v opensrc >/dev/null || { echo "install first: npm i -g opensrc"; exit 1; }

SPECS=(
  "RhysSullivan/executor"
  "modelcontextprotocol/typescript-sdk"
  "modelcontextprotocol/servers"
  "quickjs-emscripten"
  "openapi-typescript"
  "swagger-api/swagger-parser"
  "zod"
  "@apidevtools/swagger-parser"
  "ajv"
  "@modelcontextprotocol/server"
  "@modelcontextprotocol/client"
)

mkdir -p opensrc
OUT=opensrc/REFERENCES.md
TEMP=$(mktemp opensrc/.references.XXXXXX)
trap 'rm -f "$TEMP"' EXIT
echo "# Reference sources" > "$TEMP"
echo "" >> "$TEMP"
echo "Generated by scripts/refs.sh. Paths are in the opensrc cache." >> "$TEMP"
echo "" >> "$TEMP"
failed=0
for s in "${SPECS[@]}"; do
  if p=$(opensrc path "$s") && test -d "$p"; then
    reference_path="${p/#$HOME/\~}"
    echo "- \`$s\`: $reference_path" >> "$TEMP"
    echo "ok   $s"
  else
    echo "fail $s"
    failed=1
  fi
done
if test "$failed" -ne 0; then
  echo "Some references failed; existing index preserved." >&2
  exit 1
fi
mv "$TEMP" "$OUT"
echo "wrote $OUT"
